### ISSUE TITLE
Qt Demo: no change for alpha=0.5

### ISSUE THREAD

**Issue by sirop** [ejmahler/SplineLibrary#12]
Hello.
![cat_mull_rom_05](https://user-images.githubusercontent.com/1533811/35774655-3f1bd138-0976-11e8-8b28-eb8cc0724c18.png)

As you see in the pic above, the centripetal variation **does not** avoid certain types of self-intersections...

It could be however a pure Qt problem, as startin the app from the Qt Creator I get warnings:

> QMetaObject::connectSlotsByName: No matching signal for on_lineEdit_changed(QString)
> QMetaObject::connectSlotsByName: No matching signal for on_checkBox_changed(bool)
> QMetaObject::connectSlotsByName: No matching signal for on_spinBox_changed(int)
> QMetaObject::connectSlotsByName: No matching signal for on_doubleSpinBox_changed(double)
> QMetaObject::connectSlotsByName: No matching signal for on_slider_changed(int)

My OS: Windows 8.1
Qt versions I tried out: 5.8 an 5.9.1, both 64 bit.
Compiler: MSVC 2015 in both cases.

**Comment by ejmahler** [comment]
Based on your setup, it looks like it isn't actually passing the alpha value to the spline.

Does the alpha value have any effect for the natural spline?

I'll have time to investigate this tomorrow.

**Comment by sirop** [comment]
>Does the alpha value have any effect for the natural spline?

Good point. Seems to me that Catmull-Rom and Natural Spline are mixed up:

![natural_spline_05](https://user-images.githubusercontent.com/1533811/35774786-61d7c386-097a-11e8-9d50-f8d8b81dec2e.png)


As you see, in case of the two very close points one has now no "intersection" or "loop" as before.

**Comment by sirop** [comment]
Tested also with Desktop_Qt_5_6_2_MinGW_32bit. The situation is the same.

So not a matter of Qt version or compiler?

**Comment by ejmahler** [comment]
I made a push that should fix this. If you're still having the problem please re-open this bug :)

Thanks for reporting this!

**Comment by sirop** [comment]
These warnings:
>Starting D:\QtProjects\build-SplineDemo-Desktop_Qt_5_9_1_MSVC2015_64bit-Release\release\SplineDemo.exe...
QMetaObject::connectSlotsByName: No matching signal for on_lineEdit_changed(QString)
QMetaObject::connectSlotsByName: No matching signal for on_checkBox_changed(bool)
QMetaObject::connectSlotsByName: No matching signal for on_spinBox_changed(int)
QMetaObject::connectSlotsByName: No matching signal for on_doubleSpinBox_changed(double)
QMetaObject::connectSlotsByName: No matching signal for on_slider_changed(int)

remain, at least if started from within QtCreator. The rest works as it should.

**Comment by ejmahler** [comment]
Those warnings are because of the naming convention I used for generic event handlers in the settings -- it's trying to auto-connect those methods to widgets on the settings window, and harmlessly failing. Wt only tries to autoconnect methods with that naming convention, so I should change the naming of those methods to fix that. Like I said it should be completely harmless though
