### ISSUE TITLE
QVector2D compile issue

### ISSUE THREAD

**Issue by kyjak** [ejmahler/SplineLibrary#16]
hello,
can anybody watching/discussing this repo provide an example how to use the library
without QT?
Basically a bootstart simple example how to instantiate the spline?
I tried to exchange QVector2D for Vector2 but not working.
thanks a lot

**Comment by sirop** [comment]
> It expects the vector to have an API matching Qt's QVector2D class, but will support data with any dimension. Custom classes may be used as long as they provide the same public methods as QVector2D.
https://github.com/ejmahler/SplineLibrary/blob/master/docs/SplineAPI.md

This means you have to create your own _QVector2D_ in order to get along without Qt.

**Comment by kyjak** [comment]
Ok, will do, thanks
