### ISSUE TITLE
Is that kind of spline curve the same as in AutoCAD?

### ISSUE THREAD

**Issue by sorrowfeng** [ejmahler/SplineLibrary#23]
I've tried each and there are differences, the closest is UniformCubicBSpline, but there is still a difference, how do I make adjustments?

- AutoCAD
![image](https://github.com/ejmahler/SplineLibrary/assets/61925560/f0f9df4e-4d71-407a-b9cc-70591314bcd2)

- UniformCubicBSpline parsing result
![image](https://github.com/ejmahler/SplineLibrary/assets/61925560/eb2ef47b-f7b8-4a02-9640-a3f3c508affa)

**Comment by tmxfh** [comment]
nurbs++&nbsp; Library




大脸猫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ejmahler/SplineLibrary"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月26日(星期五) 上午9:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ejmahler/SplineLibrary] Is that kind of spline curve the same as in AutoCAD? (Issue #23)





 
I've tried each and there are differences, the closest is UniformCubicBSpline, but there is still a difference, how do I make adjustments?
  
 
AutoCAD
 image.png (view on web)
 
 
 
UniformCubicBSpline parsing result
 image.png (view on web)
