### ISSUE TITLE
Strange results comparing arcLength and totalLength

### ISSUE THREAD

**Issue by ban-dana** [ejmahler/SplineLibrary#4]
I'm playing with the demo and see the following: with the default point values, immediately after creating the spline, spline.arcLength(0, spline.getMaxT()) is not equal to spline.totalLength(), and the difference is quite significant (1699.87671 for the arcLength, 1666.14331 for the totalLength). This is for Normal Cubic Spline.

**Comment by ejmahler** [comment]
Could you paste the input points you used to get this result? Or if you got this spline via the GUI demo program, could you post a screenshot of the spline so I can reproduce it?

**Comment by ejmahler** [comment]
Oh, I see you said default point values. Thanks, I'll investigate this tonight

**Comment by ejmahler** [comment]
I've found the problem and I'm working on a solution. I expect to have it pushed in the next couple days. Thanks for pointing this out!

**Comment by ejmahler** [comment]
I fixed this and added unit tests to cover it. Thanks for pointing it out.

**Comment by ban-dana** [comment]
Wow, that was fast! Thanks a lot!
