### ISSUE TITLE
Feature request: equidistant split of a spline

### ISSUE THREAD

**Issue by ban-dana** [ejmahler/SplineLibrary#6]
Would be nice to have an API to equidistantly split a spline, like this:
std::vector<floating_t> Spline::splitByDistance (floating_t distance, floating_t tolerance)

Then the use case would be
std::vector<floating_t> result = aSpline.splitByDistance(distance, tolerance)

meeting this condition:
fabs (aSpline.arcLength (result[i], result[i+1]), distance) < tolerance

Apparently there is an implementation for matlab: https://se.mathworks.com/matlabcentral/fileexchange/34874-interparc

**Comment by ejmahler** [comment]
- The you link you posted cuts the spline into n equidistant pieces - is that what you're looking for? or to specify an arbitrary distance and cut the spline into chunks of that distance?
- If it's the latter, what if the spline's length isn't evenly divisible by the distance? There will be a leftover chunk at the end that's smaller than the rest
- Are you looking for equidistant points via euclidean distance between points, or equidistant in arc length between points?

**Comment by ban-dana** [comment]
You're right, it's 2 different things, sorry about the confusion.
What I need is to split the path into chunks of predefined **arc** length. If the spline isn't evenly divisible by the distance, then the remainder is "dropped". Then we can know there was a remainder by looking at the last value in the result vector.
Based on the code example above:

fabs (result.back() - aSpline.getMaxT()) > tolerance
&&
(distance - aSpline.arcLength (result.back(), aSpline.getMaxT())) > tolerance

**Comment by ejmahler** [comment]
I've decided that the api will be:

Add a new function to the Spline interface:

`floating_t inverseArcLength(floating_t a, floating_t length) const;`

This functions computes b such that `spline.arcLength(a,b) == t`

IE

```
float a = 0.5, b = 0.75;
float arcLength = spline.arcLength(a,b);
float computedB = spline.inverseArcLength(a, arcLength);

assert(qFuzzyCompare(b, computedB);
```

Make sense? The idea being, you can easily get your use case (splitting the whole spline into segments of a predefined length) vis something like this:

```
std::vector<float> result { 0.0f };
float desiredLength = 1.2f;
float a = 0f;
while(a < spline.getMaxT()) {
     float b = spline.inverseArcLength(a, desiredLength);
     result.push_back(b);
     a = b;
}
return result;
```

This ends up wasting a very small amount of work, compared to a function that has access to the internal data of the spline -- it wastes one integral for each call, specifically, so if you're dividing your spline into hundreds of chunks, you would waste hundreds of integrals.

But this will be computing dozens of integrals per call anyways, because it has to do a bisection method or boost::brentq call. So the wasted work will be a drop in the bucket.

**Comment by ejmahler** [comment]
Two things,

I'm not happy with the name of the function. It's mathematically correct, but it doesn't really document itself if you get what i mean. any suggestions for a more clear name than "inverseArcLength"?

And how do you feel about a boost dependency? To do this in an even slightly fast way requires access to boost's brent method: http://www.boost.org/doc/libs/1_61_0/libs/math/doc/html/math_toolkit/roots/brent_minima.html

Without it, I can write a bisection method but it'll be slow and less-well-tested.

**Comment by ban-dana** [comment]
So basically you're going to solve the equation spline.arcLength(t0, t0 + t) = desiredLength as if you had no idea what arcLength() does? I was hoping that knowing the internals of the spline and the arcLength calculation could help to do it more effectively than the generic root finding problem... 
Anyhow, regarding the name - easy one would be "getParameterAtArcLength" but it's ugly...  Maybe just "slice" ?

**Comment by ejmahler** [comment]
Yes and no. I can definitely make it faster than solving spline.arcLength(a, a + t), but through things like cache friendliness rather than gymnastics with the mathematics.

Computing the arc length requires a numeric integral, making it pretty opaque to things like algebra cancellations and such.

**Comment by ejmahler** [comment]
There's an implementation for this in the "arc-length-inverse" branch. I ended up changing my mind and implementing it in a separate file -- check out `spline_library/arclength.h`, the function is called "partition"

Let me know if this is what you're looking for.
